server:
  port: 8080

spring:
  application:
    name: nacos-discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.99:8848
        metadata:
          name1: healthy1
          name2: healthy2